In [1]:
import xgboost as xbg
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
import pickle
import joblib

%matplotlib inline

def load_p(fname):
    return np.array(pickle.load(open(fname,"rb")))

In [2]:
X_train = load_p("/scratch/pbanerj6/sml-dataset/X_train_cls.p")
X_val = load_p("/scratch/pbanerj6/sml-dataset/X_val_cls.p")
X_test = load_p("/scratch/pbanerj6/sml-dataset/X_test_cls.p")

In [7]:
y_train = load_p("/scratch/pbanerj6/sml-dataset/y_train.p")
y_val = load_p("/scratch/pbanerj6/sml-dataset/y_val.p")
y_test = load_p("/scratch/pbanerj6/sml-dataset/y_test.p")

In [38]:
import torch
from torch import nn, optim
from torch.optim import lr_scheduler
from torch.autograd import Variable
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from tqdm import tqdm
import os

In [5]:
class MyDataset(Dataset):
    def __init__(self, data, target, transform=None):
        self.data = torch.from_numpy(data).float()
        self.target = torch.from_numpy(target).long()
        self.transform = transform
        
    def __getitem__(self, index):
        x = self.data[index]
        y = self.target[index]
        
        if self.transform:
            x = self.transform(x)
        
        return x, y
    
    def __len__(self):
        return len(self.data)

In [8]:
train_dataset = MyDataset(X_train,y_train)
val_dataset = MyDataset(X_val,y_val)
test_dataset = MyDataset(X_test,y_test)

In [36]:
train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
    num_workers=20,
    pin_memory=torch.cuda.is_available()
)

val_loader = DataLoader(
    val_dataset,
    batch_size=64,
    shuffle=True,
    num_workers=20,
    pin_memory=torch.cuda.is_available()
)

In [28]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 768, 100, 2

In [44]:
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)
loss_fn = nn.CrossEntropyLoss()


In [45]:
def accuracy(out, labels):
    outputs = np.argmax(out, axis=1)
    return np.sum(outputs == labels)

In [46]:
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

patience = 20

max_val_acc = 0.0
for t in tqdm(range(100),desc="Epoch"):
    model.train()
    total_loss = 0.0
    tmp_acc = 0.0
    steps = 0
    nb_eval_examples = 0
    for batch_idx, (x, y) in enumerate(train_loader):
        steps+=1
        logits = model(x)
        loss = loss_fn(logits, y)
        logits = logits.detach().cpu().numpy()
        label_ids = y.to('cpu').numpy()
        tmp_acc += accuracy(logits, label_ids)
        # Compute and print loss.
        
        total_loss += loss.item()
        # Before the backward pass, use the optimizer object to zero all of the
        # gradients for the variables it will update (which are the learnable
        # weights of the model). This is because by default, gradients are
        # accumulated in buffers( i.e, not overwritten) whenever .backward()
        # is called. Checkout docs of torch.autograd.backward for more details.
        optimizer.zero_grad()

        # Backward pass: compute gradient of the loss with respect to model
        # parameters
        loss.backward()

        # Calling the step function on an Optimizer makes an update to its
        # parameters
        optimizer.step()
        nb_eval_examples += x.size(0)
    
    model.eval()
    val_acc = 0.0
    steps = 0
    nb_val_examples = 0
    for batch_idx, (x, y) in enumerate(val_loader):
        steps+=1
        logits = model(x)
        logits = logits.detach().cpu().numpy()
        label_ids = y.to('cpu').numpy()
        val_acc += accuracy(logits, label_ids)
        nb_val_examples += x.size(0)
    
    if max_val_acc < val_acc/nb_val_examples:
        patience = 20
        print("Saving Best Model!!")
        max_val_acc = val_acc/nb_val_examples
        model_to_save = model.module if hasattr(model, 'module') else model  # Only save the model it-self
        output_model_file = os.path.join("/scratch/pbanerj6/sml-nn-v1", "best_model.bin")
        torch.save(model_to_save.state_dict(), output_model_file)
    else:
        patience-=1
        
    if patience == 0:
        print("Validation Accuracy Did Not Improve After", patience, "Epochs. Stopping.")
        break
    
    
    print("Epoch:",t,"Loss:",total_loss/steps,"Train Accuracy:",(tmp_acc/nb_eval_examples),"Val Accuracy:",(val_acc/nb_val_examples))






Epoch:   0%|          | 0/100 [00:00<?, ?it/s]



Epoch:   1%|          | 1/100 [00:06<10:05,  6.12s/it]

Saving Best Model!!
Epoch: 0 Loss: 3.0374531435205583 Train Accuracy: 0.6661066666666666 Val Accuracy: 0.6308666666666667






Epoch:   2%|▏         | 2/100 [00:12<10:06,  6.19s/it]

Saving Best Model!!
Epoch: 1 Loss: 2.8943424049844135 Train Accuracy: 0.69176 Val Accuracy: 0.6354666666666666






Epoch:   3%|▎         | 3/100 [00:18<10:04,  6.23s/it]

Saving Best Model!!
Epoch: 2 Loss: 2.8238755752431586 Train Accuracy: 0.7038933333333334 Val Accuracy: 0.6417333333333334






Epoch:   4%|▍         | 4/100 [00:25<10:01,  6.26s/it]

Saving Best Model!!
Epoch: 3 Loss: 2.7748367848548483 Train Accuracy: 0.71164 Val Accuracy: 0.6422






Epoch:   5%|▌         | 5/100 [00:31<09:58,  6.30s/it]

Saving Best Model!!
Epoch: 4 Loss: 2.7284936917589064 Train Accuracy: 0.7178533333333333 Val Accuracy: 0.6466666666666666






Epoch:   6%|▌         | 6/100 [00:37<09:53,  6.31s/it]

Saving Best Model!!
Epoch: 5 Loss: 2.6911727192554067 Train Accuracy: 0.7235466666666667 Val Accuracy: 0.6491333333333333






Epoch:   7%|▋         | 7/100 [00:44<09:48,  6.33s/it]

Epoch: 6 Loss: 2.651421767219584 Train Accuracy: 0.7290266666666667 Val Accuracy: 0.6484






Epoch:   8%|▊         | 8/100 [00:50<09:43,  6.35s/it]

Epoch: 7 Loss: 2.6127709174409826 Train Accuracy: 0.73604 Val Accuracy: 0.6462






Epoch:   9%|▉         | 9/100 [00:57<09:38,  6.36s/it]

Epoch: 8 Loss: 2.5818602658332663 Train Accuracy: 0.7399333333333333 Val Accuracy: 0.6465333333333333






Epoch:  10%|█         | 10/100 [01:03<09:33,  6.38s/it]

Epoch: 9 Loss: 2.549862065594247 Train Accuracy: 0.7448 Val Accuracy: 0.6469333333333334






Epoch:  11%|█         | 11/100 [01:09<09:27,  6.38s/it]

Epoch: 10 Loss: 2.5151162000412635 Train Accuracy: 0.7500133333333333 Val Accuracy: 0.6342666666666666






Epoch:  12%|█▏        | 12/100 [01:16<09:20,  6.37s/it]

Saving Best Model!!
Epoch: 11 Loss: 2.484058116851969 Train Accuracy: 0.7552666666666666 Val Accuracy: 0.6528






Epoch:  13%|█▎        | 13/100 [01:22<09:13,  6.36s/it]

Epoch: 12 Loss: 2.450418405837201 Train Accuracy: 0.7598666666666667 Val Accuracy: 0.648






Epoch:  14%|█▍        | 14/100 [01:28<09:08,  6.38s/it]

Epoch: 13 Loss: 2.4258130823044066 Train Accuracy: 0.7638 Val Accuracy: 0.6495333333333333






Epoch:  15%|█▌        | 15/100 [01:35<09:05,  6.41s/it]

Epoch: 14 Loss: 2.3912981623030722 Train Accuracy: 0.7695466666666667 Val Accuracy: 0.6463333333333333






Epoch:  16%|█▌        | 16/100 [01:41<08:58,  6.41s/it]

Epoch: 15 Loss: 2.3614929432564593 Train Accuracy: 0.7712 Val Accuracy: 0.652






Epoch:  17%|█▋        | 17/100 [01:48<08:54,  6.43s/it]

Epoch: 16 Loss: 2.3364090257502617 Train Accuracy: 0.77648 Val Accuracy: 0.6494






Epoch:  18%|█▊        | 18/100 [01:54<08:50,  6.47s/it]

Epoch: 17 Loss: 2.299413210660853 Train Accuracy: 0.78188 Val Accuracy: 0.6260666666666667






Epoch:  19%|█▉        | 19/100 [02:01<08:46,  6.50s/it]

Epoch: 18 Loss: 2.27184642984512 Train Accuracy: 0.7859333333333334 Val Accuracy: 0.6463333333333333






Epoch:  20%|██        | 20/100 [02:08<08:41,  6.52s/it]

Epoch: 19 Loss: 2.2428841673313302 Train Accuracy: 0.7899066666666666 Val Accuracy: 0.6410666666666667






Epoch:  21%|██        | 21/100 [02:14<08:39,  6.58s/it]

Epoch: 20 Loss: 2.210780473719252 Train Accuracy: 0.7945866666666667 Val Accuracy: 0.6456666666666667






Epoch:  22%|██▏       | 22/100 [02:21<08:35,  6.61s/it]

Epoch: 21 Loss: 2.18314991504588 Train Accuracy: 0.79848 Val Accuracy: 0.6492






Epoch:  23%|██▎       | 23/100 [02:28<08:32,  6.65s/it]

Epoch: 22 Loss: 2.1525408451861523 Train Accuracy: 0.8029066666666667 Val Accuracy: 0.6441333333333333






Epoch:  24%|██▍       | 24/100 [02:34<08:24,  6.64s/it]

Epoch: 23 Loss: 2.1237802666552525 Train Accuracy: 0.8052666666666667 Val Accuracy: 0.6501333333333333






Epoch:  25%|██▌       | 25/100 [02:41<08:19,  6.66s/it]

Epoch: 24 Loss: 2.095063101991694 Train Accuracy: 0.8105066666666667 Val Accuracy: 0.6375333333333333






Epoch:  26%|██▌       | 26/100 [02:48<08:12,  6.66s/it]

Epoch: 25 Loss: 2.0622087647306158 Train Accuracy: 0.8145333333333333 Val Accuracy: 0.6309333333333333






Epoch:  27%|██▋       | 27/100 [02:54<08:06,  6.67s/it]

Epoch: 26 Loss: 2.0360078594786057 Train Accuracy: 0.8179733333333333 Val Accuracy: 0.6516666666666666






Epoch:  28%|██▊       | 28/100 [03:01<08:02,  6.70s/it]

Epoch: 27 Loss: 2.004934127153234 Train Accuracy: 0.8229333333333333 Val Accuracy: 0.6484666666666666






Epoch:  29%|██▉       | 29/100 [03:08<07:55,  6.70s/it]

Epoch: 28 Loss: 1.9750343447035932 Train Accuracy: 0.8254533333333334 Val Accuracy: 0.6331333333333333






Epoch:  30%|███       | 30/100 [03:14<07:47,  6.68s/it]

Epoch: 29 Loss: 1.9451167130089821 Train Accuracy: 0.83032 Val Accuracy: 0.6379333333333334






Epoch:  31%|███       | 31/100 [03:21<07:40,  6.67s/it]

Epoch: 30 Loss: 1.918594585644438 Train Accuracy: 0.8346533333333334 Val Accuracy: 0.6406
Validation Accuracy Did Not Improve After 0 Epochs. Stopping.


In [47]:
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)
output_model_file = os.path.join("/scratch/pbanerj6/sml-nn-v1", "best_model.bin")
model.load_state_dict(torch.load(output_model_file))
model.eval()

Sequential(
  (0): Linear(in_features=768, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=2, bias=True)
)

In [56]:
from scipy.stats import rankdata
from scipy.special import softmax

def mrrs(out, labels):
    print(out)
    outputs = np.argmax(out,axis=1)
    mrr = 0.0 
    for label,ranks in zip(labels,out):
        ranks = rankdata(ranks*-1)
        rank = ranks[label]
        mrr+=1/rank
    return mrr/len(labels)

def mrrwrapper(qid2c,qid2indexmap,preds_prob):
    labels = []
    out = []
    for qid in qid2c.keys():
        scores = []
        for ix in qid2indexmap[qid]:
            if len(scores) < 6:
                scores.append(preds_prob[ix][1])
        if len(scores) < 6:
            continue
        out.append(scores)
        labels.append(int(qid2c[qid]))
    return mrrs(np.array(out),labels)

def load_ranking(fname):
    return pickle.load(open("/scratch/pbanerj6/sml-dataset/ranking_"+fname+".p","rb"))

qid2c,qid2indexmap = load_ranking("test")

model.eval()
val_acc = 0.0
steps = 0
nb_val_examples = 0

test_loader = DataLoader(
    test_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=20,
    pin_memory=torch.cuda.is_available()
)

all_preds = []

for batch_idx, (x, y) in enumerate(test_loader):
    logits = model(x)
    logits = logits.detach().cpu().numpy()
    
    for pred in logits:
        all_preds.append(softmax(pred))
    
    label_ids = y.to('cpu').numpy()
    val_acc += accuracy(logits, label_ids)
    nb_val_examples += x.size(0)
    
mrr = mrrwrapper(qid2c,qid2indexmap,all_preds)
print("Test Accuracy:",(val_acc/nb_val_examples),"MRR:",(mrr))

[[0.36931092 0.4086804  0.2969394  0.0818483  0.16670115 0.18603277]
 [0.456922   0.6600688  0.07702929 0.7353013  0.8406557  0.64199984]
 [0.45062605 0.3171125  0.23331673 0.25553235 0.8806134  0.75682116]
 ...
 [0.01513177 0.16570406 0.02787823 0.05568737 0.21851334 0.12771149]
 [0.7124999  0.78986394 0.79848343 0.4941654  0.5839576  0.6593364 ]
 [0.31009448 0.6777135  0.50702024 0.6136262  0.7772534  0.5065988 ]]
Test Accuracy: 0.6520666666666667 MRR: 0.5982222222222253
